import {useEffect,useRef,useState} from 'react';
import {Avatar,avatarFromFile} from './media';
import {api} from './api';
export function CommunitySettings({me,act,call,output,setOutput,sensitivity,setSensitivity,setError,setNotice,copy,busy,ready,onLogout}:any){
 const [tab,setTab]=useState('profile'),[profile,setProfile]=useState({name:me?.name||localStorage.getItem('voz-name')||'Visitante',avatar:me?.avatar||localStorage.getItem('voz-avatar')||'',status:me?.status||'',presence:me?.presence||'online'}),[key,setKey]=useState(''),[devices,setDevices]=useState<MediaDeviceInfo[]>([]);const photo=useRef<HTMLInputElement>(null);
 useEffect(()=>{const update=()=>navigator.mediaDevices?.enumerateDevices().then(setDevices).catch(()=>{});void update();navigator.mediaDevices?.addEventListener('devicechange',update);return()=>navigator.mediaDevices?.removeEventListener('devicechange',update)},[call.joined]);
 async function save(){const r=await act('profile',profile);if(r){localStorage.setItem('voz-name',profile.name);localStorage.setItem('voz-avatar',profile.avatar);if(call.joined)await call.updateProfile(profile.name,profile.avatar);setNotice('Perfil salvo.')}}
 async function restore(){const value=key.trim();if(!/^[a-f0-9-]{36}\.[a-f0-9]{64}$/i.test(value)){setError('Chave inválida.');return}const old=localStorage.getItem('tatico-credential');localStorage.setItem('tatico-credential',value);try{await api('poll');location.reload()}catch(e:any){if(old)localStorage.setItem('tatico-credential',old);else localStorage.removeItem('tatico-credential');setError(e.message)}}
 return <><div className="settings-tabs">{[['profile','Meu perfil'],['audio','Voz e vídeo'],['access','Acesso']].map(([k,v])=><button className={tab===k?'selected':''} key={k} onClick={()=>setTab(k)}>{v}</button>)}</div>
 {tab==='profile'&&<div className="modal-stack"><div className="profile-preview"><Avatar src={profile.avatar} name={profile.name} className="profile-avatar"/><button onClick={()=>photo.current?.click()}>Trocar avatar</button><button onClick={()=>setProfile(p=>({...p,avatar:''}))}>Remover</button></div><input ref={photo} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={async e=>{const f=e.target.files?.[0];if(f)try{const avatar=await avatarFromFile(f);setProfile(p=>({...p,avatar}))}catch(e:any){setError(e.message)}}}/><label>Nome<input maxLength={30} value={profile.name} onChange={e=>setProfile(p=>({...p,name:e.target.value}))}/></label><label>Status personalizado<input maxLength={100} value={profile.status} placeholder="O que está acontecendo?" onChange={e=>setProfile(p=>({...p,status:e.target.value}))}/></label><label>Presença<select value={profile.presence} onChange={e=>setProfile(p=>({...p,presence:e.target.value}))}><option value="online">Online</option><option value="away">Ausente</option><option value="busy">Ocupado</option></select></label><button className="primary" disabled={busy||!ready} onClick={()=>void save()}>Salvar perfil</button></div>}
 {tab==='audio'&&<div className="modal-stack"><label>Microfone<select value={call.inputDeviceId} onChange={e=>void call.switchMicrophone(e.target.value)}><option value="">Padrão do sistema</option>{devices.filter(d=>d.kind==='audioinput').map((d,i)=><option key={d.deviceId||i} value={d.deviceId}>{d.label||'Microfone '+(i+1)}</option>)}</select></label><label>Saída de áudio<select disabled={!('setSinkId' in HTMLMediaElement.prototype)} value={output} onChange={e=>setOutput(e.target.value)}><option value="">Padrão do sistema</option>{devices.filter(d=>d.kind==='audiooutput').map((d,i)=><option key={d.deviceId||i} value={d.deviceId}>{d.label||'Saída '+(i+1)}</option>)}</select></label><p>Os nomes dos dispositivos aparecem após permitir o microfone. A seleção de saída depende do navegador.</p><label className="check-label"><input type="checkbox" checked={call.voiceProcessing} onChange={e=>void call.setVoiceProcessing(e.target.checked)}/> Redução de ruído e cancelamento de eco</label><label>Detecção de fala<select value={sensitivity} onChange={e=>setSensitivity(e.target.value)}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option></select></label><label>Qualidade de transmissão<select value={call.shareQuality} onChange={e=>void call.setShareQuality(e.target.value)}>{[['stable','540p'],['balanced','720p'],['high','1080p'],['ultra','1440p'],['4k','4K adaptativo']].map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><p>Até 4K, conforme tela, navegador e rede. Mais participantes reduzem a qualidade disponível. {call.turnConfigured?'TURN configurado.':'TURN não detectado.'}</p></div>}
 {tab==='access'&&<div className="modal-stack"><p>Sua identidade usa uma chave privada guardada neste navegador. Guarde uma cópia para restaurar seu acesso em outro dispositivo. Quem tiver a chave poderá usar seu perfil.</p><button onClick={()=>void copy(localStorage.getItem('tatico-credential')||'')}>Copiar minha chave de acesso</button><label>Restaurar identidade<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder="Cole sua chave privada"/></label><button className="primary" onClick={()=>void restore()}>Restaurar acesso</button><p>Ao sair, esta conta deixa de ficar salva neste navegador. O app abre uma identidade nova, e a conta antiga só poderá ser recuperada com a chave copiada.</p><button className="danger" onClick={onLogout}>Sair da conta</button></div>}</>;
}
