import {ScreenPanel} from './screen-panel';
'use client';
import {useEffect,useRef,useState} from 'react';
import {Shield,Hash,Volume2,Plus,Settings,Users,Mic,MicOff,Headphones,PhoneOff,MonitorUp,Send,Pin,Reply,MessageCircle,Copy,Search,ChevronDown,Menu,Radio,Trash2,Pencil,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useCall,type ShareQuality} from './use-call';
import {api} from './api';
import {useCommunity} from './use-community';
import {Avatar,Media,SpeakingSensor,avatarFromFile,unlockRoomAudio} from './media';
import {CommunitySettings} from './community-settings';
type Channel={id:string;name:string;kind:'text'|'voice';roomKey:string};
const roles:Record<string,string>={owner:'Dono',admin:'Administrador',moderator:'Moderador',member:'Membro'};
const states:Record<string,string>={online:'Online',away:'Ausente',busy:'Ocupado',offline:'Offline'};
const qualities:Record<ShareQuality,string>={stable:'540p',balanced:'720p',high:'1080p',ultra:'1440p','4k':'4K adaptativo'};
export default function Home(){
 const {data:d,selection:s,select,act,error,setError,ready,busy}=useCommunity();
 const [draft,setDraft]=useState(''),[reply,setReply]=useState<any>(null),[editing,setEditing]=useState<any>(null),[pins,setPins]=useState(false),[members,setMembers]=useState(true),[nav,setNav]=useState(false),[search,setSearch]=useState('');
 const [modal,setModal]=useState(''),[input,setInput]=useState(''),[kind,setKind]=useState('text'),[notice,setNotice]=useState('');
 const [voice,setVoice]=useState<Channel|null>(null),[deaf,setDeaf]=useState(false),[speaking,setSpeaking]=useState<Record<string,boolean>>({}),[presence,setPresence]=useState<any[]>([]);
 const [output,setOutput]=useState(()=>localStorage.getItem('voz-output-device')||''),[sensitivity,setSensitivity]=useState<'low'|'normal'|'high'>('normal');
 const muteBefore=useRef(false),typingAt=useRef(0),bottom=useRef<HTMLDivElement>(null),atBottom=useRef(true);
 const group=d.groups.find((g:any)=>g.id===s.groupId),channel:Channel|undefined=d.channels.find((c:Channel)=>c.id===s.channelId),me=d.me;
 const call=useCall(voice?.roomKey.slice(37)||'Lounge',group?.space||'');
 const manage=['owner','admin'].includes(group?.role),moderate=['owner','admin','moderator'].includes(group?.role);
 const person=d.members.find((m:any)=>m.userKey===s.dmTarget),title=s.dmTarget?person?.name||'Mensagem direta':channel?.name||'Sua central';
 useEffect(()=>{const code=new URL(location.href).searchParams.get('invite');if(code&&ready){setInput(code);setModal('join')}},[ready]);
 useEffect(()=>{setDraft('');setReply(null);setEditing(null);setPins(false);atBottom.current=true},[s.groupId,s.channelId,s.dmTarget]);
 useEffect(()=>{if(atBottom.current&&!s.before)bottom.current?.scrollIntoView({block:'end'})},[d.messages.length,d.dms.length,s.channelId,s.dmTarget]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{if(!call.joined)setDeaf(false)},[call.joined]);
 useEffect(()=>{localStorage.setItem('voz-output-device',output)},[output]);
 useEffect(()=>{if(!group)return;let alive=true,t:any;const poll=async()=>{try{const r=await fetch('/api/presence?space='+group.space,{headers:{Authorization:'Bearer '+localStorage.getItem('tatico-credential')}});const j=await r.json();if(alive&&r.ok)setPresence(j.peers||[])}catch{}finally{if(alive)t=setTimeout(poll,2000)}};void poll();return()=>{alive=false;clearTimeout(t);setPresence([])}},[group?.id]);
 useEffect(()=>{if(voice&&!d.channels.some((c:Channel)=>c.id===voice.id)){call.leave();setVoice(null)}},[d.channels]);
 function navigate(next:any){select(next);setNav(false)}
 function switchGroup(id:string){if(busy)return;if(id!==group?.id){call.leave();setVoice(null);navigate({groupId:id,channelId:'',dmTarget:''})}}
 async function enter(c:Channel){if(call.space!==group?.space){setNotice('Preparando a sala. Tente novamente em um instante.');return}if(call.busy||busy||call.joined&&voice?.id===c.id)return;call.leave();setVoice(c);setSpeaking({});await unlockRoomAudio();await call.join(me?.name||'Visitante',me?.avatar||'',c.roomKey.slice(37))}
 function deafen(){if(!deaf){muteBefore.current=call.muted;if(!call.muted)call.toggleMute();setDeaf(true)}else{setDeaf(false);if(!muteBefore.current&&call.muted)call.toggleMute()}}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setNotice('Copiado.')}catch{setNotice(text)}}
 function open(k:string,v=''){setInput(v);setModal(k)}
 async function submit(){let extra:any={};if(['create','rename','channelRename','channelCreate'].includes(modal))extra={name:input,kind};if(modal==='join')extra={code:input};if(modal==='deleteMessage')extra={messageId:Number(input)};const j=await act(modal,extra);if(j){if(['create','join','delete','leave'].includes(modal)){call.leave();setVoice(null)}setModal('');setNotice('Alteração concluída.');if(modal==='join'){const url=new URL(location.href);url.searchParams.delete('invite');history.replaceState(null,'',url)}}}
 async function send(){if(!draft.trim())return;const j=await act(s.dmTarget?'dmSend':editing?'editMessage':'message',{message:draft,target:s.dmTarget,replyId:reply?.id,messageId:editing?.id,nonce:crypto.randomUUID()});if(j){setDraft('');setReply(null);setEditing(null);atBottom.current=true}}
 function type(text:string){setDraft(text);if(!s.dmTarget&&Date.now()-typingAt.current>2500){typingAt.current=Date.now();void api('typing',s).catch(()=>{})}}
 const rows=s.dmTarget?d.dms:pins?d.pinned:d.messages;
 const titles:Record<string,string>={create:'Criar servidor',join:'Entrar em um servidor',rename:'Renomear servidor',channelCreate:'Criar canal',channelRename:'Renomear canal',delete:'Excluir servidor?',leave:'Sair do servidor?',channelDelete:'Excluir canal?',invite:'Revogar convite atual?',deleteMessage:'Excluir mensagem?'};
 const destructive=['delete','leave','channelDelete','invite','deleteMessage'].includes(modal);
 return <div className={'tactical-app '+(nav?'nav-open':'')}>
 <nav className="server-rail" aria-label="Servidores"><div className="brand-mark" title="Vértice"><Shield size={26}/></div><div className="rail-line"/>{d.groups.map((g:any)=><button key={g.id} title={g.name} aria-label={g.name} aria-current={g.id===group?.id} className={'server-icon '+(g.id===group?.id?'selected':'')} onClick={()=>switchGroup(g.id)}>{g.name.slice(0,2).toUpperCase()}</button>)}<button className="server-icon add" aria-label="Criar servidor" title="Criar servidor" onClick={()=>open('create')}><Plus/></button><button className="server-icon" aria-label="Entrar por convite" title="Entrar por convite" onClick={()=>open('join')}><Users size={21}/></button><span className="rail-bottom">V / 01</span></nav>
 <aside className="sidebar"><header className="server-heading"><div><small>VÉRTICE / COMUNIDADES</small><strong>{group?.name||'Sua central'}</strong></div><button aria-label="Gerenciar servidor" disabled={!group} onClick={()=>open('server')}><ChevronDown size={18}/></button></header><div className="channel-search"><Search size={16}/><input aria-label="Buscar canal" placeholder="Encontrar canal" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 <div className="channel-list">{['text','voice'].map(k=><section key={k}><div className="category"><span>{k==='text'?'CANAIS DE TEXTO':'CANAIS DE VOZ'}</span>{manage&&<button aria-label={'Criar canal de '+(k==='text'?'texto':'voz')} onClick={()=>{setKind(k);open('channelCreate')}}><Plus size={15}/></button>}</div>{d.channels.filter((c:Channel)=>c.kind===k&&c.name.toLowerCase().includes(search.toLowerCase())).map((c:Channel)=><div key={c.id}><button className={'channel-button '+(c.id===channel?.id&&!s.dmTarget?'active':'')} onClick={()=>{navigate({channelId:c.id,dmTarget:''});if(c.kind==='voice')void enter(c)}}>{k==='text'?<Hash size={19}/>:<Volume2 size={19}/>}<span>{c.name}</span>{call.joined&&voice?.id===c.id&&<i className="status-dot online"/>}</button>{k==='voice'&&presence.filter(p=>c.roomKey===group.space+'-'+p.channel).map(p=><div className="voice-person" key={p.id}><i className="status-dot online"/>{p.name}</div>)}</div>)}</section>)}
 <section><div className="category"><span>MENSAGENS DIRETAS</span><MessageCircle size={14}/></div>{d.members.filter((m:any)=>m.userKey!==me?.userKey).map((m:any)=><button key={m.userKey} className={'channel-button '+(s.dmTarget===m.userKey?'active':'')} onClick={()=>navigate({dmTarget:m.userKey})}><Avatar name={m.name} src={m.avatar} className="mini-avatar"/><span>{m.name}</span><i className={'status-dot '+m.presence}/></button>)}{d.members.length<2&&<p className="sidebar-hint">Convide alguém para começar uma conversa.</p>}</section></div>
 {call.joined&&<div className="connection-panel"><span><Radio size={16}/> Voz conectada</span><strong>{voice?.name}</strong><button aria-label="Desconectar voz" onClick={()=>{call.leave();setVoice(null)}}><PhoneOff size={18}/></button><button className="share-shortcut" onClick={()=>void call.share()}><MonitorUp size={16}/>{call.sharing?'Parar transmissão':'Transmitir tela'}</button></div>}
 <div className="user-panel"><button onClick={()=>open('settings')} aria-label="Editar perfil"><Avatar src={me?.avatar} name={me?.name||'V'} className="user-avatar"/></button><div className="user-info"><strong>{me?.name||'Visitante'}</strong><small><i className={'status-dot '+(me?.presence||'offline')}/>{states[me?.presence||'offline']}</small></div><button title="Microfone" aria-label="Silenciar microfone" disabled={!call.joined||deaf} className={call.muted?'danger':''} onClick={call.toggleMute}>{call.muted?<MicOff size={17}/>:<Mic size={17}/>}</button><button title="Ensurdecer" aria-label="Ensurdecer" disabled={!call.joined} className={deaf?'danger':''} onClick={deafen}><Headphones size={17}/></button><button title="Configurações" aria-label="Configurações" onClick={()=>open('settings')}><Settings size={17}/></button></div></aside>
 <main className="workspace"><header className="topbar"><button className="mobile-menu" aria-label="Mostrar canais" onClick={()=>setNav(v=>!v)}><Menu size={20}/></button><div className="room-title">{s.dmTarget?<MessageCircle size={22}/>:channel?.kind==='voice'?<Volume2 size={22}/>:<Hash size={22}/>}<strong>{title}</strong><span>{s.dmTarget?'Mensagem direta':channel?.kind==='voice'?'Sala de voz':'Conversa da equipe'}</span></div><div className="header-actions">{group&&<button title="Convidar pessoas" aria-label="Convidar pessoas" onClick={()=>open('server')}><Users size={20}/></button>}{channel&&!s.dmTarget&&<><button title="Mensagens fixadas" aria-label="Mensagens fixadas" className={pins?'accent':''} onClick={()=>setPins(v=>!v)}><Pin size={19}/></button>{manage&&<button title="Editar canal" aria-label="Editar canal" onClick={()=>open('channelRename',channel.name)}><Pencil size={18}/></button>}</>}<button title="Lista de membros" aria-label="Lista de membros" onClick={()=>setMembers(v=>!v)}><Menu size={20}/></button></div></header>
 {(error||notice||call.error)&&<div className={'feedback '+(error?'error':'')} role="status">{error||notice||call.error}<button aria-label="Fechar aviso" onClick={()=>{setError('');setNotice('')}}><X size={15}/></button></div>}
 <div className="workspace-body"><div className="conversation">
 {!group?<div className="welcome"><div className="welcome-emblem"><Shield size={44}/></div><small>SEU PONTO DE ENCONTRO</small><h1>Uma base para sua equipe.</h1><p>Reúna suas pessoas. Organize as conversas.<br/>Entre na voz quando quiser.</p><div className="welcome-actions"><button className="primary" disabled={!ready} onClick={()=>open('create')}><Plus size={18}/> Criar servidor</button><button className="secondary" disabled={!ready} onClick={()=>open('join')}>Tenho um convite</button></div>{!ready&&<button onClick={()=>open('settings')}>Restaurar chave de acesso</button>}</div>:<>
 {channel?.kind==='voice'&&!s.dmTarget&&<div className="voice-stage"><div className="stage-heading"><div><small>CANAL DE VOZ</small><h2>{channel.name}</h2></div>{(!call.joined||voice?.id!==channel.id)&&<button className="primary" disabled={call.busy} onClick={()=>void enter(channel)}><Mic size={17}/>{call.busy?'Conectando…':'Entrar na voz'}</button>}</div>{call.joined&&<><SpeakingSensor stream={call.localStream} enabled={!call.muted} sensitivity={sensitivity} onChange={v=>call.self&&setSpeaking(old=>old[call.self!]===v?old:{...old,[call.self!]:v})}/><div className="participant-grid">{call.people.map(p=><div className={'participant '+(speaking[p.id]?'speaking':'')} key={p.id}><Avatar name={p.name} src={call.avatars[p.id]} className="participant-avatar"/><strong>{p.name}</strong><small>{speaking[p.id]?'Falando':p.id===call.self?(call.muted?'Microfone desligado':'Você'):(call.peerStates[p.id]==='connected'?'Conectado':'Conectando…')}</small></div>)}</div><div className="voice-controls"><button onClick={()=>void call.share()}><MonitorUp size={17}/>{call.sharing?'Parar tela':'Transmitir'}</button><select aria-label="Qualidade da transmissão" value={call.shareQuality} onChange={e=>void call.setShareQuality(e.target.value as ShareQuality)}>{Object.entries(qualities).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button onClick={()=>{void unlockRoomAudio();call.repairAudio()}}>Reconectar áudio</button></div></>}</div>}
 <div className="messages" onScroll={e=>{const el=e.currentTarget;atBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<90}}><div className="chat-intro"><span className="chat-symbol">{s.dmTarget?<MessageCircle size={26}/>:<Hash size={28}/>}</span><h2>{pins?'Mensagens fixadas':s.dmTarget?title:'Bem-vindo a #'+title}</h2><p>{pins?'Os recados importantes ficam por aqui.':s.dmTarget?'Uma conversa entre vocês.':'Este é o começo da conversa. Faça parte.'}</p></div>
 {!pins&&<div className="history-controls">{s.before>0&&<button onClick={()=>navigate({before:0})}>Voltar às mais recentes</button>}{rows.length===80&&<button onClick={()=>navigate({before:rows[0].id})}>Carregar anteriores</button>}</div>}{!rows.length&&<p className="empty-message">{pins?'Nenhuma mensagem fixada.':'Nenhuma mensagem por aqui ainda.'}</p>}
 {rows.map((m:any)=>{const sender=s.dmTarget?m.sender:m.userKey,p=d.members.find((p:any)=>p.userKey===sender),mine=sender===me?.userKey;return <article className="message" key={m.id}><Avatar src={p?.avatar} name={p?.name||m.name||'Membro'} className="message-avatar"/><div className="message-content"><div className="message-head"><strong>{p?.name||m.name||'Membro'}</strong>{mine&&<span className="you-tag">VOCÊ</span>}<time dateTime={new Date(m.created).toISOString()}>{new Date(m.created).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</time>{m.edited&&<small>(editada)</small>}{!!m.pinned&&<Pin size={12}/>}</div>{m.reply&&<blockquote>{m.reply.name}: {m.reply.body}</blockquote>}<p>{m.body}</p>{!s.dmTarget&&<div className="reactions">{m.reactions.map((r:any)=><button key={r.emoji} className={r.mine?'mine':''} onClick={()=>void act('react',{messageId:m.id,emoji:r.emoji})}>{r.emoji} {r.count}</button>)}</div>}</div>{!s.dmTarget&&<div className="message-tools"><button title="Responder" aria-label="Responder" onClick={()=>{setReply(m);setEditing(null)}}><Reply size={15}/></button><details><summary aria-label="Adicionar reação">☺</summary><div className="emoji-picker">{['👍','❤️','🔥','😂','✅'].map(emoji=><button key={emoji} onClick={ev=>{void act('react',{messageId:m.id,emoji});ev.currentTarget.closest('details')?.removeAttribute('open')}}>{emoji}</button>)}</div></details>{mine&&<button title="Editar" aria-label="Editar mensagem" onClick={()=>{setEditing(m);setDraft(m.body);setReply(null)}}><Pencil size={14}/></button>}{moderate&&<button title="Fixar ou desafixar" aria-label="Fixar ou desafixar" onClick={()=>void act('pin',{messageId:m.id})}><Pin size={14}/></button>}{(mine||moderate)&&<button title="Excluir" aria-label="Excluir mensagem" onClick={()=>open('deleteMessage',String(m.id))}><Trash2 size={14}/></button>}</div>}</article>})}<div ref={bottom}/></div>
 <div className="compose-area">{(reply||editing)&&<div className="reply-bar">{editing?'Editando sua mensagem':'Respondendo a '+reply.name}<button aria-label="Cancelar edição ou resposta" onClick={()=>{setReply(null);setEditing(null);setDraft('')}}><X size={16}/></button></div>}<form className="composer" onSubmit={e=>{e.preventDefault();void send()}}><textarea aria-label="Mensagem" placeholder={'Conversar em '+(s.dmTarget?title:'#'+title)} maxLength={2000} rows={1} value={draft} disabled={(!channel&&!s.dmTarget)||!!s.dmTarget&&!d.dmAllowed} onChange={e=>type(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}}/><button className="send-button" type="submit" aria-label="Enviar mensagem" disabled={busy||!draft.trim()||!!s.dmTarget&&!d.dmAllowed}><Send size={19}/></button></form><div className="composer-meta"><span>{!s.dmTarget&&d.typing.length?d.typing.map((p:any)=>p.name).join(', ')+' digitando…':s.dmTarget&&!d.dmAllowed?'É necessário um servidor em comum.':'Enter para enviar · Shift + Enter para nova linha'}</span><span>{draft.length}/2000</span></div></div>
 </>}</div>
 {members&&group&&<aside className="members-panel"><div className="category">MEMBROS — {d.members.length}</div>{['online','away','busy','offline'].map(status=><section key={status}>{d.members.some((m:any)=>m.presence===status)&&<h3>{states[status]}</h3>}{d.members.filter((m:any)=>m.presence===status).map((m:any)=><div className="member-row" key={m.userKey}><button className="member-main" title={m.status||m.name} onClick={()=>{if(m.userKey!==me?.userKey)navigate({dmTarget:m.userKey});else open('settings')}}><span className="member-avatar"><Avatar src={m.avatar} name={m.name} className="member-photo"/><i className={'status-dot '+m.presence}/></span><span><strong>{m.name}</strong><small>{m.status||roles[m.role]}</small></span></button>{group.role==='owner'&&m.role!=='owner'&&<select aria-label={'Cargo de '+m.name} value={m.role} onChange={e=>void act('role',{target:m.userKey,role:e.target.value})}>{['member','moderator','admin'].map(r=><option key={r} value={r}>{roles[r]}</option>)}</select>}</div>)}</section>)}<div className="members-footer"><Shield size={16}/><span>VÉRTICE<br/><small>Seu espaço. Sua equipe.</small></span></div></aside>}
 </div></main>
 {call.joined&&<div className="call-media">{call.people.filter(p=>p.id!==call.self&&call.streams[p.id]).map(p=><Media key={p.id} stream={call.streams[p.id]} audioMuted={deaf} outputDeviceId={output} sensitivity={sensitivity} onSpeaking={v=>setSpeaking(old=>old[p.id]===v?old:{...old,[p.id]:v})}/>)}</div>}
 {(call.screen||Object.values(call.remoteSharing).some(Boolean))&&<ScreenPanel><header><MonitorUp size={16}/> Transmissões <button onClick={()=>void call.share()}>{call.sharing?'Parar minha tela':'Transmitir'}</button></header>{call.screen&&<div><small>Sua tela</small><Media stream={call.screen} local forceVideo/></div>}{call.people.filter(p=>call.remoteSharing[p.id]).map(p=><div key={p.id}><small>{p.name}</small>{call.screenStreams[p.id]?<Media stream={call.screenStreams[p.id]} forceVideo audioMuted={deaf} outputDeviceId={output}/>:<p>Conectando transmissão…</p>}</div>)}</ScreenPanel>}
 <Dialog open={!!modal} onOpenChange={v=>!v&&setModal('')}><DialogContent className={'tactical-modal '+(modal==='settings'?'settings-modal':'')}><DialogTitle>{modal==='settings'?'Configurações':modal==='server'?group?.name:titles[modal]||'Vértice'}</DialogTitle><DialogDescription>{modal==='settings'?'Seu perfil e suas preferências de voz.':modal==='server'?'Convide sua equipe e organize o servidor.':destructive?'Confira a ação antes de continuar.':'Escolha como sua equipe vai se encontrar.'}</DialogDescription>
 {modal==='server'&&group&&<div className="modal-stack"><label>CONVITE DO SERVIDOR<input readOnly value={location.origin+'/?invite='+group.inviteCode}/></label><button className="primary" onClick={()=>void copy(location.origin+'/?invite='+group.inviteCode)}><Copy size={16}/> Copiar link</button><button onClick={()=>void copy(group.inviteCode)}>Copiar código: {group.inviteCode}</button>{manage&&<><button onClick={()=>open('rename',group.name)}>Renomear servidor</button><button onClick={()=>open('invite')}>Gerar novo convite</button></>}{group.role==='owner'?<button className="danger" onClick={()=>open('delete')}>Excluir servidor</button>:<button className="danger" onClick={()=>open('leave')}>Sair do servidor</button>}</div>}
 {titles[modal]&&<form className="modal-stack" onSubmit={e=>{e.preventDefault();void submit()}}>{destructive?<p>{modal==='invite'?'O link e o código atuais deixarão de funcionar. Os membros permanecem no servidor.':modal==='leave'?'Você precisará de um convite para entrar novamente.':'Esta ação apaga o conteúdo selecionado e não pode ser desfeita.'}</p>:<label>{modal==='join'?'Código ou link de convite':'Nome'}<input autoFocus maxLength={modal==='join'?300:40} value={input} onChange={e=>setInput(e.target.value)} required/></label>}{modal==='channelCreate'&&<label>Tipo<select value={kind} onChange={e=>setKind(e.target.value)}><option value="text">Texto</option><option value="voice">Voz</option></select></label>}<button type="submit" className="primary" disabled={busy||(!destructive&&!input.trim())}>{busy?'Salvando…':destructive?'Confirmar':'Salvar'}</button>{modal==='channelRename'&&<button type="button" className="danger" onClick={()=>open('channelDelete')}>Excluir este canal</button>}</form>}
 {modal==='settings'&&<CommunitySettings me={me} act={act} call={call} output={output} setOutput={setOutput} sensitivity={sensitivity} setSensitivity={setSensitivity} setError={setError} setNotice={setNotice} copy={copy} busy={busy} ready={ready}/>}
 {error&&<p className="modal-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 </DialogContent></Dialog></div>;
}


