'use client';
import { useEffect,useRef,useState } from 'react';
type Person={id:string;name:string};
export function useCall(channel:string){
 const [people,setPeople]=useState<Person[]>([]),[streams,setStreams]=useState<Record<string,MediaStream>>({}),[joined,setJoined]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[muted,setMuted]=useState(false),[sharing,setSharing]=useState(false),[screen,setScreen]=useState<MediaStream|null>(null),[space,setSpace]=useState('');
 const session=useRef<any>(null),mic=useRef<MediaStream|null>(null),display=useRef<MediaStream|null>(null),connections=useRef<Record<string,RTCPeerConnection>>({}),pending=useRef<Record<string,RTCIceCandidateInit[]>>({});
 useEffect(()=>{let key=location.hash.slice(1);if(!/^[a-f0-9-]{36}$/.test(key)){key=crypto.randomUUID();history.replaceState(null,'','#'+key)}setSpace(key);return()=>{cleanup()}},[]);
 function cleanup(){session.current=null;mic.current?.getTracks().forEach(t=>t.stop());display.current?.getTracks().forEach(t=>t.stop());Object.values(connections.current).forEach(p=>p.close());connections.current={};pending.current={};mic.current=null;display.current=null;}
 async function request(action:string,extra:any={},s=session.current){if(!s)throw Error('Entre na call primeiro.');const r=await fetch('/api/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,room:s.room,id:s.id,token:s.token,after:s.after,...extra}),keepalive:action==='leave'});const j:any=await r.json();if(!r.ok)throw Error(j.error||'Falha na conexão.');return j}
 function leave(){const s=session.current;if(s)void request('leave',{},s).catch(()=>{});cleanup();setJoined(false);setPeople([]);setStreams({});setScreen(null);setSharing(false);setMuted(false)}
 function connection(id:string,s:any){if(connections.current[id])return connections.current[id];const p=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}]});connections.current[id]=p;
 p.addTransceiver(mic.current!.getAudioTracks()[0],{direction:'sendrecv',streams:[mic.current!]});const v=p.addTransceiver('video',{direction:'sendrecv'});if(display.current)void v.sender.replaceTrack(display.current.getVideoTracks()[0]);
 p.onicecandidate=e=>{if(e.candidate)void request('signal',{target:id,data:{candidate:e.candidate.toJSON()}},s).catch(e=>setError(e.message))};
 p.ontrack=e=>{setStreams(old=>{const stream=old[id]||new MediaStream();if(!stream.getTracks().some(t=>t.id===e.track.id))stream.addTrack(e.track);return {...old,[id]:stream}})};
 p.onconnectionstatechange=()=>{if(p.connectionState==='failed')setError('Não foi possível conectar com uma pessoa. Tentem outra rede e entrem novamente.');};return p}
 async function apply(j:any,s:any){if(session.current!==s)return;setPeople(j.peers);const ids=new Set(j.peers.map((p:Person)=>p.id));for(const id of Object.keys(connections.current)){if(!ids.has(id)){connections.current[id].close();delete connections.current[id];setStreams(o=>{const n={...o};delete n[id];return n})}}
 for(const person of j.peers as Person[]){if(person.id!==s.id && s.id<person.id && !connections.current[person.id]){const p=connection(person.id,s);await p.setLocalDescription(await p.createOffer());await request('signal',{target:person.id,data:{description:p.localDescription}},s)}}
 for(const signal of j.signals){s.after=Math.max(s.after,signal.id);if(!ids.has(signal.sender))continue;const data=JSON.parse(signal.data),p=connection(signal.sender,s);if(data.description){await p.setRemoteDescription(data.description);for(const c of pending.current[signal.sender]||[])await p.addIceCandidate(c);pending.current[signal.sender]=[];if(data.description.type==='offer'){await p.setLocalDescription(await p.createAnswer());await request('signal',{target:signal.sender,data:{description:p.localDescription}},s)}}else if(data.candidate){if(p.remoteDescription)await p.addIceCandidate(data.candidate);else(pending.current[signal.sender]??=[]).push(data.candidate)}}}
 async function join(name:string){setBusy(true);setError('');try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Abra o site em uma janela segura do Chrome ou Edge para usar o microfone.');mic.current=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});const s={room:space+'-'+channel,id:crypto.randomUUID(),token:crypto.randomUUID(),after:0};session.current=s;await apply(await request('join',{name:name.trim()||'Visitante'},s),s);setJoined(true);void poll(s)}catch(e:any){leave();setError(e.name==='NotAllowedError'?'Permita o microfone no navegador e tente novamente.':e.message)}finally{setBusy(false)}}
 async function poll(s:any){while(session.current===s){await new Promise(r=>setTimeout(r,1500));if(session.current!==s)return;try{await apply(await request('poll',{},s),s)}catch(e:any){if(session.current!==s)return;setError(e.message);leave();return}}}
 function toggleMute(){const next=!muted;mic.current?.getAudioTracks().forEach(t=>t.enabled=!next);setMuted(next)}
 async function stopScreen(){display.current?.getTracks().forEach(t=>t.stop());display.current=null;setScreen(null);setSharing(false);await Promise.all(Object.values(connections.current).map(p=>p.getTransceivers().find(t=>t.receiver.track.kind==='video')?.sender.replaceTrack(null)))}
 async function share(){setError('');if(sharing){await stopScreen();return}try{if(!navigator.mediaDevices?.getDisplayMedia)throw Error('O compartilhamento de tela está disponível no Chrome ou Edge no computador.');const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});display.current=stream;setScreen(stream);setSharing(true);const track=stream.getVideoTracks()[0];track.onended=()=>{void stopScreen()};await Promise.all(Object.values(connections.current).map(p=>p.getTransceivers().find(t=>t.receiver.track.kind==='video')?.sender.replaceTrack(track)))}catch(e:any){if(e.name!=='NotAllowedError')setError(e.message)}}
 async function invite(){try{await navigator.clipboard.writeText(location.href);setError('Link copiado! Envie para sua galera entrar na mesma sala.')}catch{setError('Copie o endereço da barra do navegador para convidar.')}}
 return {people,streams,joined,busy,error,muted,sharing,screen,join,leave,toggleMute,share,invite,self:session.current?.id};
}


